from typing import Protocol, List
from domain.entities import Item

class ItemRepository(Protocol):
    async def save(self, item: Item) -> Item: ...
    async def get_by_id(self, item_id: str) -> Item | None: ...
    async def delete(self, item_id: str) -> bool: ...
    async def list_all(self) -> List[Item]: ...
